name: rent2ownwelcomeapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+4

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0
  rxdart: ^0.27.7
  workmanager: ^0.5.1
  geolocator: ^12.0.0
  phone_number: ^2.1.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  collection: ^1.17.1
  usage_stats: ^1.2.0
  app_settings: ^5.1.1
  
  # Network 
  http: ^1.2.1
  dio: ^5.2.1+1
  connectivity_plus: ^6.0.3
  chuck_interceptor: ^2.1.6
  crypto: ^3.0.3 #for MD5
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.1.0

  # Data
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.0

  # State Management
  provider: ^6.0.3
  state_notifier: ^1.0.0

  # Handler 
  permission_handler: ^11.3.1

  # Services
  mobile_number: ^2.1.1
  flutter_sms_inbox: ^1.0.2
  call_log: ^4.0.0
  fast_contacts: ^3.0.3
  installed_apps: ^1.3.1
  app_usage: ^3.0.1
  battery_plus: ^6.0.1
  check_vpn_connection: ^0.0.2

  # Socail Packs
  flutter_facebook_auth: ^7.0.0
  flutter_tiktok_sdk: ^0.2.5
  
  # Storage
  shared_preferences: ^2.1.1
  
  # UI
  loader_overlay: ^4.0.0
  gif_view: ^0.4.3
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  fluttertoast: ^8.2.1
  # sms_otp_auto_verify: ^2.1.0
  sms_otp_auto_verify:
    git:
      url: https://github.com/TandohAnthonyNwiAckah/sms_otp_auto_verify.git
      ref: d321a9c7a25e17eeb4d5a2e8ba4d170978811a81
  flutter_launcher_icons: ^0.13.1
  flutter_widget_from_html: ^0.15.0
  flutter_localization: ^0.2.0
  flutter_html: ^3.0.0-beta.2
  dartz: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  retrofit_generator: ^8.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/home.png"



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/operators/

  